### ISSUE TITLE
Client sending 'stop' message which is causing exceptions in Coniql (Strawberry version)

### ISSUE THREAD

**Issue by rjwills28** [dls-controls/cs-web-lib#17]
I've opened this issue to log the problem I have just found but I note that it will solved simply by updating to the new graphql websocket protocol is cs-web-lib. 

We recently made a change discussed in issue #11 (PR #12) to stop duplicate subscriptions being sent to Coniql when the client browser reconnects to the server. This occurred in the case where we load our webpage, bring Coniql down and then start again. The change we made means that if we have not received acknowledgment of the connection then we throw an error: https://github.com/dls-controls/cs-web-lib/blob/3453939456917a6e2a1fbafed9042dc9045ebfa6/src/connection/coniql.ts#L310. Underneath the hood, the apollographql client sends a 'stop' message to the server if there is an error (see apollographql issue [9109](https://github.com/apollographql/apollo-client/issues/9109).

I have been testing the machine status application (which uses cs-web-lib) with the new Coniql version using the Strawberry graphql api. I found that the Strawberry code starts throwing exceptions constantly when running against the latest version of cs-web-lib (with the above fix). Note that this does not happen when running against the original cs-web-proto. 

What is happening is that the first thing being received by Coniql when it starts up again is the 'stop' message from the client. When Strawberry receives a 'stop' message it tries to close the subscription, indexing a dictionary with the ID. However, in this case we never started a subscription and so we get a key error. The client is still waiting for the acknowledgment and has not received it as Coniql is throwing errors, hence it keeps throwing errors, which keeps sending 'stop' messages, which continues to cause error in Coniql (and so we go on forever)...

As noted above, this issue does not appear when running against cs-web-proto or the version of cs-web-proto using the new graphql-transport-ws protocol hence I have pinned the issue down to our current subscription method in cs-web-lib.

To fix this in cs-web-lib I would change line [310](https://github.com/dls-controls/cs-web-lib/blob/3453939456917a6e2a1fbafed9042dc9045ebfa6/src/connection/coniql.ts#L310) to log a warning instead of throwing an error causing the 'stop' message to be sent:
```
console.warn("Acknowledgment not received from server.");
```

This needs to be done when we switch to the new version of Coniql, although at this point the strategy may be to move cs-web-lib to the new graphql websocket protocol immediately.

**Comment by aawdls** [comment]
Can you paste an example exception seen in the Coniql logs?

**Comment by rjwills28** [comment]
Example of exception seen:
```
Error handling request
Traceback (most recent call last):
  File "/home/cnuser/.local/share/virtualenvs/coniql-W5jWBl11/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/cnuser/.local/share/virtualenvs/coniql-W5jWBl11/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/cnuser/.local/share/virtualenvs/coniql-W5jWBl11/lib/python3.8/site-packages/strawberry/aiohttp/views.py", line 65, in __call__
    return await self.graphql_ws_handler_class(
  File "/home/cnuser/.local/share/virtualenvs/coniql-W5jWBl11/lib/python3.8/site-packages/strawberry/subscriptions/protocols/graphql_ws/handlers.py", line 70, in handle
    return await self.handle_request()
  File "/home/cnuser/.local/share/virtualenvs/coniql-W5jWBl11/lib/python3.8/site-packages/strawberry/aiohttp/handlers/graphql_ws_handler.py", line 48, in handle_request
    await self.handle_message(message)
  File "/home/cnuser/.local/share/virtualenvs/coniql-W5jWBl11/lib/python3.8/site-packages/strawberry/subscriptions/protocols/graphql_ws/handlers.py", line 85, in handle_message
    await self.handle_stop(message)
  File "/home/cnuser/.local/share/virtualenvs/coniql-W5jWBl11/lib/python3.8/site-packages/strawberry/subscriptions/protocols/graphql_ws/handlers.py", line 150, in handle_stop
    await self.cleanup_operation(operation_id)
  File "/home/cnuser/.local/share/virtualenvs/coniql-W5jWBl11/lib/python3.8/site-packages/strawberry/subscriptions/protocols/graphql_ws/handlers.py", line 192, in cleanup_operation
    await self.subscriptions[operation_id].aclose()
KeyError: '2'
```

**Comment by rjwills28** [comment]
In fact this `throw new Error("Acknowledgement not received from server."); ` is actually causing lots of errors to be thrown by the client when disconnected which I think is unnecessary. This should be changed to a `log.warn` to save an influx of errors when refreshing or cycling through pages. 

I also see the following error thrown in the client relating to the disconnect/reconnection:
```
Error: Failed to unsubscribe from pv ...
Error: TypeError: this.subscriptions[pvName] is undefined
```
We need to fix this.

**Comment by rjwills28** [comment]
Fixed in above PR.
